name: padraic-brewtarget # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.4.0-22092020' # just for humans, typically '1.2+git' or '1.3.2'
summary: Brewtarget is brewing software, FREE as in Libre & Beer. Perfect for homebrew! # 79 char long summary
description: |
    Brewtarget is FREE brewing software, and an open source beer recipe creation tool. It automatically calculates color, bitterness, and more for you while you drag and drop ingredients into the recipe. Brewtarget also has many other tools such as priming sugar calculators, OG correction help, and a unique mash designing tool. It can export and import recipes, allowing you to easily share them with friends. All of this means that Brewtarget is your single, free, go-to tool when crafting your beer recipes.
#icon:
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  padraic-brewtarget:
    command: $SNAP/bin/brewtarget
    command-chain:
     - bin/session-manager-workaround
    extensions:
      - kde-neon
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
# The session-manager-workaround launcher: Silent error messages due to inaccessible paths
# https://forum.snapcraft.io/t/the-session-manager-workaround-launcher-silent-error-messages-due-to-inaccessible-paths/20252
  session-manager-workaround:
    source: https://github.com/Lin-Buo-Ren/session-manager-workaround-launch.git
    source-tag: v1.0.0
    plugin: dump
    stage:
      - bin/*
  my-part:
    # See 'snapcraft plugins'
    source: .
  #source-branch: devel
    plugin: cmake
    build-packages: [g++, cmake, git, qtbase5-dev, qttools5-dev, qttools5-dev-tools, qtmultimedia5-dev, libqt5sql5-sqlite, libqt5sql5-psql, libqt5svg5-dev, libqt5multimedia5-plugins, doxygen]

    stage-packages:
     - libasyncns0
     - libdouble-conversion1
     - libflac8
     - libfreetype6
     - libgl1
     - libglvnd0
     - libglx0
     - libgraphite2-3
     - libharfbuzz0b
     - libicu60
     - libogg0
     - libpng16-16
     - libpulse0
     - libqt5core5a
     - libqt5gui5
     - libqt5multimedia5
     - libqt5network5
     - libqt5printsupport5
     - libqt5sql5
     - libqt5sql5-sqlite
     - libqt5widgets5
     - libqt5xml5
     - libsndfile1
     - libsqlite3-0
     - libvorbis0a
     - libvorbisenc2
     - libx11-6
     - libxau6
     - libxcb1
     - libxdmcp6
     - sqlitebrowser
